### PR TITLE
[EAP 6.4] Update build for new repo configs and increase the timeout needed  to clean up after patching

### PR DESCRIPTION
**Pull request by luck3y**
Signed-off-by: Ken Wills <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Comment by bstansberry** [comment]
What's the JIRA for this timeout change? 180 secs seems like a very long time.

The timeout change vs the build eye of newt stuff seem like distinct issues.

**Comment by luck3y** [comment]
@bstansberry There isn't one, I can make one though. They are somewhat distinct, but I can't successfully run a build of this on my machine with the default timeout, it always exceeds it. OSBS, on the other hand, it works fine.

**Comment by bstansberry** [comment]
@luck3y OK, I wasn't thinking right. This timeout is just part of the image build, it's not a runtime timeout. So I'm not particularly concerned about a JIRA for it.

180 secs seems really long though, particularly for a shutdown.

**Review by bstansberry — APPROVED** [review]

**Comment by luck3y** [comment]
Yeah, the value is somewhere > 30 and < 180, but given that its likely just my machine being slow, picking an actual number didn't seem to make much sense. Actually on the shutdown, its probably not needed, so I can probably reset that to 30s again.

**Pull request merged**
