### PR TITLE
CLOUD-2969 move to rhel7 base image; move product installation to mod…

### PR DESCRIPTION
**Pull request by rcernich**
…ules
https://issues.jboss.org/browse/CLOUD-2969
Signed-off-by: rcernich <rcernich@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for other issues
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

### CODE REVIEW

**Review by luck3y — DISMISSED** [review]

**Comment by vhalbert** [comment]
Are there any plans to move the eap modules to the eap-modules repo for use by extending products, or is the expectation is to add this repo as a module repo in the yaml file?

**Comment by luck3y** [comment]
@vhalbert We'll be moving the eap modules to jboss-eap-modules.

**Comment by bstansberry** [comment]
@vhalbert @luck3y Maybe they will not move. Please see the cloud-enablement list post I just submitted.  I don't think they are a good fit for jboss-eap-modules.

**Comment by luck3y** [comment]
@bstansberry Perhaps I misinderstood @vhalbert's question, I took it to be referring to the EAP modules in cct_module, not the ones local to the image. So, I think the answer to the local modules here should be no, but the cct_module ones, yes.

**Comment by luck3y** [comment]
In fact, after writing this, I'm pretty sure I misunderstood, sorry :(

**Comment by rcernich** [comment]
The idea behind this change is that you would include this repo as a module repository.  Whether or not these modules might move to another repository in the future is a question for the EAP team.

**Comment by bstansberry** [comment]
@rcernich How about adding that idea you had re: JBOSS_MODULES_SYSTEM_LPKGS? I did that in the EAP 7.2 variant and it solved the problem with building an OS image from the modules without the standalone image layer:

https://github.com/jboss-container-images/jboss-eap-7-image/pull/105/files#diff-b19e4d60a31d5464e0cbe04627f5f30aR22

and 

https://github.com/jboss-container-images/jboss-eap-7-image/pull/105/files#diff-b19e4d60a31d5464e0cbe04627f5f30aR52

**Comment by bstansberry** [comment]
@apintea Look ok to you?

**Review by luck3y — APPROVED** [review]

**Pull request merged**
